name: cdk diff

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - ready_for_review

jobs:
  cdk_diff:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: setup go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.24.3"

      - name: aws authenticate
        uses: aws-actions/configure-aws-credentials@v4.2.1
        with:
          role-to-assume: arn:aws:iam::123456789012:role/cdk-diff-action-sample
          aws-region: ap-northeast-1

      - name: cdk synth
        run: npx cdk synth

      - name: cdk diff
        uses: corymhall/cdk-diff-action@v1.4.18
        with:
          failOnDestructiveChanges: false
          githubToken: ${{ secrets.GITHUB_TOKEN }}
